
TOKEN = "7835241498:AAEf2h8t7A2EP066aShar_oCHEtEUYZYAhw" # API токен бота - @BotFather
ADMINS = [5501024918] # Администраторы бота, айди можно получить через - @getmyid_bot
BOT_USERNAME = "Danbesy_Parser_Bot" # Юзернейм бота
LOGS_CHANNEL_ID = -1002545497657 # Айди канала с логами при авто-парсинге

GIFTS = [
    "AstralShard", "BDayCandle", "BerryBox", "BunnyMuffin", "CandyCane", "CookieHeart", "CrystalBall",
    "DeskCalendar", "DiamondRing", "DurovsCap", "ElectricSkull", "EternalCandle", "EternalRose",
    "EvilEye", "FlyingBroom", "GenieLamp", "GingerCookie", "HangingStar", "HexPot", "HomemadeCake",
    "HypnoLollipop", "IonGem", "JackInTheBox", "JellyBunny", "JesterHat", "JingleBells", "KissedFrog", "LolPop",
    "LootBag", "LoveCandle", "LovePotion", "LunarSnake", "MadPumpkin", "MagicPotion", "MiniOscar",
    "NekoHelmet", "PartySparkler", "PerfumeBottle", "PlushPepe", "PreciousPeach", "RecordPlayer",
    "SakuraFlower", "SantaHat", "ScaredCat", "SharpTongue", "SignetRing", "SkullFlower", "SleighBell",
    "SnowGlobe", "SnowMittens", "SpicedWine", "SpyAgaric", "StarNotepad", "SwissWatch", "TamaGadget",
    "TopHat", "ToyBear", "TrappedHeart", "VintageCigar", "VoodooDoll", "WinterWreath", "WitchHat"
]

GIFTS_NAME_WITH_LINKS = {
    "AstralShard": "<b><a href='https://t.me/addemoji/AstralShardSkins'>🌌 Astral Shard</a></b>",
    "BDayCandle": "<b><a href='https://t.me/addemoji/BDayCandleSkins'>🕯️ B-Day Candle</a></b>",
    "BerryBox": "<b><a href='https://t.me/addemoji/BerryBoxSkins'>🍓 Berry Box</a></b>",
    "BunnyMuffin": "<b><a href='https://t.me/addemoji/BunnyMuffinSkins'>🧁 Bunny Muffin</a></b>",
    "CandyCane": "<b><a href='https://t.me/addemoji/CandyCaneSkins'>🍬 Candy Cane</a></b>",
    "CookieHeart": "<b><a href='https://t.me/addemoji/CookieHeartSkins'>🍪 Cookie Heart</a></b>",
    "CrystalBall": "<b><a href='https://t.me/addemoji/CrystalBallSkins'>🔮 Crystal Ball</a></b>",
    "DeskCalendar": "<b><a href='https://t.me/addemoji/DeskCalendarSkins'>📅 Desk Calendar</a></b>",
    "DiamondRing": "<b><a href='https://t.me/addemoji/DiamondRingSkins'>💍 Diamond Ring</a></b>",
    "DurovsCap": "<b><a href='https://t.me/addemoji/DurovsCapSkins'>🧢 Durov’s Cap</a></b>",
    "ElectricSkull": "<b><a href='https://t.me/addemoji/ElectricSkullSkins'>💀 Electric Skull</a></b>",
    "EternalCandle": "<b><a href='https://t.me/addemoji/EternalCandleSkins'>🕯️ Eternal Candle</a></b>",
    "EternalRose": "<b><a href='https://t.me/addemoji/EternalRoseSkins'>🌹 Eternal Rose</a></b>",
    "EvilEye": "<b><a href='https://t.me/addemoji/EvilEyeSkins'>👁️ Evil Eye</a></b>",
    "FlyingBroom": "<b><a href='https://t.me/addemoji/FlyingBroomSkins'>🧹 Flying Broom</a></b>",
    "GenieLamp": "<b><a href='https://t.me/addemoji/GenieLampSkins'>🛋️ Genie Lamp</a></b>",
    "GingerCookie": "<b><a href='https://t.me/addemoji/GingerCookieSkins'>🍪 Ginger Cookie</a></b>",
    "HangingStar": "<b><a href='https://t.me/addemoji/HangingStarSkins'>⭐ Hanging Star</a></b>",
    "HexPot": "<b><a href='https://t.me/addemoji/HexPotSkins'>🪴 Hex Pot</a></b>",
    "HomemadeCake": "<b><a href='https://t.me/addemoji/HomemadeCakeSkins'>🍰 Homemade Cake</a></b>",
    "HypnoLollipop": "<b><a href='https://t.me/addemoji/HypnoLollipopSkins'>🍭 Hypno Lollipop</a></b>",
    "IonGem": "<b><a href='https://t.me/addemoji/IonGemSkins'>💎 Ion Gem</a></b>",
    "JackInTheBox": "<b><a href='https://t.me/addemoji/JackInTheBoxSkins'>📦 Jack-in-the-Box</a></b>",
    "JellyBunny": "<b><a href='https://t.me/addemoji/JellyBunnySkins'>🐰 Jelly Bunny</a></b>",
    "JesterHat": "<b><a href='https://t.me/addemoji/JesterHatSkins'>🎩 Jester Hat</a></b>",
    "JingleBells": "<b><a href='https://t.me/addemoji/JingleBellsSkins'>🔔 Jingle Bells</a></b>",
    "KissedFrog": "<b><a href='https://t.me/addemoji/KissedFrogSkins'>🐸 Kissed Frog</a></b>",
    "LolPop": "<b><a href='https://t.me/addemoji/LolPopSkins'>🍭 Lol Pop</a></b>",
    "LootBag": "<b><a href='https://t.me/addemoji/LootBagSkins'>🎒 Loot Bag</a></b>",
    "LoveCandle": "<b><a href='https://t.me/addemoji/LoveCandleSkins'>🕯️ Love Candle</a></b>",
    "LovePotion": "<b><a href='https://t.me/addemoji/LovePotionSkins'>💖 Love Potion</a></b>",
    "LunarSnake": "<b><a href='https://t.me/addemoji/LunarSnakeSkins'>🐍 Lunar Snake</a></b>",
    "MadPumpkin": "<b><a href='https://t.me/addemoji/MadPumpkinSkins'>🎃 Mad Pumpkin</a></b>",
    "MagicPotion": "<b><a href='https://t.me/addemoji/MagicPotionSkins'>🍷 Magic Potion</a></b>",
    "MiniOscar": "<b><a href='https://t.me/addemoji/MiniOscarSkins'>🏆 Mini Oscar</a></b>",
    "NekoHelmet": "<b><a href='https://t.me/addemoji/NekoHelmetSkins'>🐾 Neko Helmet</a></b>",
    "PartySparkler": "<b><a href='https://t.me/addemoji/PartySparklerSkins'>🎇 Party Sparkler</a></b>",
    "PerfumeBottle": "<b><a href='https://t.me/addemoji/PerfumeBottleSkins'>💐 Perfume Bottle</a></b>",
    "PlushPepe": "<b><a href='https://t.me/addemoji/PlushPepeSkins'>🐸 Plush Pepe</a></b>",
    "PreciousPeach": "<b><a href='https://t.me/addemoji/PreciousPeachSkins'>🍑 Precious Peach</a></b>",
    "RecordPlayer": "<b><a href='https://t.me/addemoji/RecordPlayerSkins'>🎶 Record Player</a></b>",
    "SakuraFlower": "<b><a href='https://t.me/addemoji/SakuraFlowerSkins'>🌸 Sakura Flower</a></b>",
    "SantaHat": "<b><a href='https://t.me/addemoji/SantaHatSkins'>🎅 Santa Hat</a></b>",
    "ScaredCat": "<b><a href='https://t.me/addemoji/ScaredCatSkins'>😺 Scared Cat</a></b>",
    "SharpTongue": "<b><a href='https://t.me/addemoji/SharpTongueSkins'>🗣️ Sharp Tongue</a></b>",
    "SignetRing": "<b><a href='https://t.me/addemoji/SignetRingSkins'>💍 Signet Ring</a></b>",
    "SkullFlower": "<b><a href='https://t.me/addemoji/SkullFlowerSkins'>💀 Skull Flower</a></b>",
    "SleighBell": "<b><a href='https://t.me/addemoji/SleighBellSkins'>🔔 Sleigh Bell</a></b>",
    "SnowGlobe": "<b><a href='https://t.me/addemoji/SnowGlobeSkins'>🌍 Snow Globe</a></b>",
    "SnowMittens": "<b><a href='https://t.me/addemoji/SnowMittensSkins'>🧤 Snow Mittens</a></b>",
    "SpicedWine": "<b><a href='https://t.me/addemoji/SpicedWineSkins'>🍷 Spiced Wine</a></b>",
    "SpyAgaric": "<b><a href='https://t.me/addemoji/SpyAgaricSkins'>🍄 Spy Agaric</a></b>",
    "StarNotepad": "<b><a href='https://t.me/addemoji/StarNotepadSkins'>📓 Star Notepad</a></b>",
    "SwissWatch": "<b><a href='https://t.me/addemoji/SwissWatchSkins'>⌚ Swiss Watch</a></b>",
    "TamaGadget": "<b><a href='https://t.me/addemoji/TamaGadgetSkins'>🎮 Tama Gadget</a></b>",
    "TopHat": "<b><a href='https://t.me/addemoji/TopHatSkins'>🎩 Top Hat</a></b>",
    "ToyBear": "<b><a href='https://t.me/addemoji/ToyBearSkins'>🐻 Toy Bear</a></b>",
    "TrappedHeart": "<b><a href='https://t.me/addemoji/TrappedHeartSkins'>💔 Trapped Heart</a></b>",
    "VintageCigar": "<b><a href='https://t.me/addemoji/VintageCigarSkins'>🚬 Vintage Cigar</a></b>",
    "VoodooDoll": "<b><a href='https://t.me/addemoji/VoodooDollSkins'>🪆 Voodoo Doll</a></b>",
    "WinterWreath": "<b><a href='https://t.me/addemoji/WinterWreathSkins'>🌲 Winter Wreath</a></b>",
    "WitchHat": "<b><a href='https://t.me/addemoji/WitchHatSkins'>🎩 Witch Hat</a></b>"
}

